name: 🐛 Bug Report
description: Something isn't working as expected 🤔
labels: ["Type: Bug"]
assignees:
  - erdaltsksn

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: Describe the bug in detail
      description: >
        A clear and concise description of what the bug is.
        What did you expect to happen and what possible solutions?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: >
        Describe the steps here. You can use code blocks here.
      value: |
        1. First, 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context info like os, version, env, path, etc.
        Here is the right place if you have relevant screenshots or log output.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/erdaltsksn/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
