name: 🚀 Feature Request
description: I have a suggestion and may want to implement it 🙂
labels: ["Type: Enhancement"]
assignees:
  - erdaltsksn

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to help us to improve this project!

  - type: textarea
    attributes:
      label: Suggest an idea for this project
      description: >
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context info like os, version, env, path, etc.
        Here is the right place if you have relevant screenshots or log output.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/erdaltsksn/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
