name: 💬 Support Question
description: You are welcome here if you have a question 🤗
labels: ["Type: Question"]
assignees:
  - erdaltsksn

body:
  - type: markdown
    attributes:
      value: >
        We are here to help!

  - type: textarea
    attributes:
      label: Details
      description: >
        Add a little context to your question.
        Describe the solutions you have tried.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context info like os, version, env, path, etc.
        Here is the right place if you have relevant screenshots or log output.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        By submitting this issue, you agree to the following statements.
      options:
        - label: "I agree to follow this project's [Code of Conduct](https://github.com/erdaltsksn/.github/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: "I've searched the issue and my question hasn't been asked before."
          required: true
        - label: "It is not a bug report or feature request."
          required: true
